os:
  - linux
  - osx

# See https://docs.travis-ci.com/user/reference/xenial/
dist: xenial
# See https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
osx_image: xcode9.2 # 10.12 w/ macosx10.13 SDK https://doc.qt.io/qt-5.12/supported-platforms.html

language: cpp

compiler:
 - gcc
 - clang

sudo: true

addons:
  apt:
    packages:
     - cmake
     # https://doc-snapshots.qt.io/qt5-5.12/linux.html
     - libgl1-mesa-dev
     # https://doc.qt.io/qt-5.12/qtwebengine-platform-notes.html#all-platforms
     - gperf
     # https://doc.qt.io/qt-5.12/qtwebengine-platform-notes.html#linux
     - libdbus-1-dev
     - libnss3-dev
     - libfontconfig1-dev # is already the newest version (2.11.94-0ubuntu1.1).
     # Qt WebEngine for xcb
     - libdrm-dev
     - libxcomposite-dev
     - libxcursor-dev
     - libxi-dev
     - libxrandr-dev
     - libxss-dev
     - libxtst-dev
     # Qt WebEngine other development packages
     - libegl1-mesa-dev
     - libcap-dev

script:
 - ./Testing/travisCITest.sh

